# Generated by Django 6.0.3 on 2026-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myblog",
            name="congratulation_sent",
            field=models.BooleanField(
                default=False, verbose_name="Поздравление отправлено"
            ),
        ),
        migrations.AddField(
            model_name="myblog",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="URL"
            ),
        ),
    ]
